[build]
builder = "NIXPACKS"
buildCommand = "cd src/server && npm install && npx prisma generate && npx tsc && cd ../client && npm install && npm run build"

[deploy]
startCommand = "cd src/server && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
